#lang sicp

(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (empty?)
      (null? front-ptr))
    (define (delete!)
      (if (empty?)
          (error "delete on an empty queue")
          (begin
            (set! front-ptr (cdr front-ptr))
            dispatch)))
    (define (front)
      (if (empty?) (error "front called on an empty queue")
      (car front-ptr)))
    (define (print)
      (display front-ptr)
      (newline))    
    (define (insert! elem)
      (let ((new-pair (cons elem '())))
        (cond ((empty?)
          (set! front-ptr new-pair)
          (set! rear-ptr new-pair)
          dispatch)
          (else
           (set-cdr! rear-ptr new-pair)
           (set! rear-ptr new-pair)
           dispatch))))
    (define (dispatch m)
      (cond ((eq? m 'empty-queue?) (empty?))
            ((eq? m 'print) (print))
            ((eq? m 'delete!) (delete!))
            ((eq? m 'front) (front))
            ((eq? m 'insert!) insert!)
            (else (error "unkown method"))))
    dispatch))

(define q (make-queue))
(q 'empty-queue?)
((q 'insert!) 'x)
((q 'insert!) 'y)
(q 'print)
(q 'front)
(q 'delete!)
(q 'front)